name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install
        
      - name: Add SWC for Linux
        run: npm i -D @swc/cli @swc/core

      - name: Start server
        run: npm run dev &
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

